### PR TITLE
AJAX OMDB

### PR DESCRIPTION
**Pull request by naynoms**
6/10
- not too hard to do but hard to remember

### CODE REVIEW

**Comment by Phoboes** [comment]
Fortunately you likely won't need to memorise that syntax for very long, even if you need to re-use it, it's easy enough to get away with copy & paste.

Digging the colour scheme.

**Comment by jburton91** [comment]
Naomi O’sullivan

Great work good to see so much homework keep up the good work!!

WK1 - THUR Missing bracket and move console.log before the  final bracket e.g.. 
}
     }
     console.log(validateCreditCard(card1));
    };
W1-WED  same problem as above console.log inside the main function and missing curly brace;
WK2- MON brooklyn your image src should look like this

WK4-MON - BMI told me I’m overweight I’m actually a healthy weight there where a few thing I found but to make it quick try this next time 

bmi = (weight / ((height/ 100) ** 2 )).round(1)
puts "Your BMI is #{bmi}"

case bmi
when 1..18.5
  puts "You are underweight. BMI below 18.5"
when 18.5..25
  puts "You are in the healthy weight range. BMI between 18.5 and 25"
when 25..30
  puts "You are overweight. BMI between 25 and 30"
else
 puts "you are overweight"
end

**Comment by jburton91** [comment]
WK2 example

**Comment by jburton91** [comment]
Naomi O’sullivan

Great work good to see so much homework keep up the good work!!

WK1 - THUR Missing bracket and move console.log before the  final bracket e.g.. 
}
     }
     console.log(validateCreditCard(card1));
    };
W1-WED  same problem as above console.log inside the main function and missing curly brace;
WK2- MON brooklyn your image src should look like this

WK4-MON - BMI told me I’m overweight I’m actually a healthy weight there where a few thing I found but to make it quick try this next time 

bmi = (weight / ((height/ 100) ** 2 )).round(1)
puts "Your BMI is #{bmi}"

case bmi
when 1..18.5
  puts "You are underweight. BMI below 18.5"
when 18.5..25
  puts "You are in the healthy weight range. BMI between 18.5 and 25"
when 25..30
  puts "You are overweight. BMI between 25 and 30"
else
 puts "you are overweight"
end

**Comment by jburton91** [comment]
Naomi O’sullivan

Great work good to see so much homework keep up the good work!!

WK1 - THUR Missing bracket and move console.log before the  final bracket e.g.. 
}
     }
     console.log(validateCreditCard(card1));
    };
W1-WED  same problem as above console.log inside the main function and missing curly brace;
WK2- MON brooklyn your image src should look like this
image
WK4-MON - BMI told me I’m overweight I’m actually a healthy weight there where a few thing I found but to make it quick try this next time 

bmi = (weight / ((height/ 100) ** 2 )).round(1)
puts "Your BMI is #{bmi}"

case bmi
when 1..18.5
  puts "You are underweight. BMI below 18.5"
when 18.5..25
  puts "You are in the healthy weight range. BMI between 18.5 and 25"
when 25..30
  puts "You are overweight. BMI between 25 and 30"
else
 puts "you are overweight"
end

**Comment by jburton91** [comment]
Naomi O’sullivan

Great work good to see so much homework keep up the good work!!

WK1 - THUR Missing bracket and move console.log before the  final bracket e.g.. 
}
     }
     console.log(validateCreditCard(card1));
    };
W1-WED  same problem as above console.log inside the main function and missing curly brace;
WK2- MON brooklyn your image src should look like this
img src=“images/example.jpg” alt=“Example image”
WK4-MON - BMI told me I’m overweight I’m actually a healthy weight there where a few thing I found but to make it quick try this next time 

bmi = (weight / ((height/ 100) ** 2 )).round(1)
puts "Your BMI is #{bmi}"

case bmi
when 1..18.5
  puts "You are underweight. BMI below 18.5"
when 18.5..25
  puts "You are in the healthy weight range. BMI between 18.5 and 25"
when 25..30
  puts "You are overweight. BMI between 25 and 30"
else
 puts "you are overweight"
end

**Pull request merged**
